### ISSUE TITLE
Which Pytorch version do we need to run the pretrained model? Pytorch version 0.3.1 and 0.3.0 give the following error.

### ISSUE THREAD

**Issue by adityarp9** [PiotrDabkowski/pytorch-saliency#1]
pytorch-saliency/saliency_eval.py", line 29, in fn
    masks, _, cls_logits = saliency(_images*2, _selectors, model_confidence=model_confidence)
lib/python2.7/site-packages/torch/nn/modules/module.py", line 325, in __call__
    result = self.forward(*input, **kwargs)
pytorch-saliency/sal/saliency_model.py", line 96, in forward
    out = self.encoder(_images)
lib/python2.7/site-packages/torch/nn/modules/module.py", line 325, in __call__
    result = self.forward(*input, **kwargs)
pytorch-saliency/sal/utils/resnet_encoder.py", line 23, in forward
    x = self.avgpool(s5)
/lib/python2.7/site-packages/torch/nn/modules/module.py", line 325, in __call__
    result = self.forward(*input, **kwargs)
lib/python2.7/site-packages/torch/nn/modules/pooling.py", line 505, in forward
    self.padding, self.ceil_mode, self.count_include_pad)
**RuntimeError: Given input size: (2048x1x1). Calculated output size: (2048x-5x-5). Output size is too small at /opt/conda/conda-bld/pytorch_1512378360668/work/torch/lib/THNN/generic/SpatialAveragePooling.c:64**

**Comment by PiotrDabkowski** [comment]
It should work with the new versions of pytorch. Does the real-time UI demo work for you?

**Comment by adityarp9** [comment]
I haven't tried the real-time UI demo. However, your code works on pytorch 0.2.0 and maybe on the earlier versions too. Right now the training seems to work. However, it throws a warning:
`WARNING: Num steps is not fully supported yet! (fix it!)`

**Comment by PiotrDabkowski** [comment]
Hmm, that would mean that they have introduced some breaking changes in the new version of PyRorch. I will look into that when I have some time. Regarding the warning just ignore it :)

**Comment by adityarp9** [comment]
Okay. Thanks :grinning:
