### ISSUE TITLE
Global variable error

### ISSUE THREAD

**Issue by serhangul** [PiotrDabkowski/pytorch-saliency#5]
I'm using Python 3.6. When I run `real_time_saliency.py`, I get this error:

>   File "real_time_saliency.py", line 315
>     global SAVE_SIGNAL
>     ^
> SyntaxError: name 'SAVE_SIGNAL' is used prior to global declaration

Any idea why this occurs? Thanks.

**Comment by PiotrDabkowski** [comment]
Easy, Python 3 is not supported :) Please use Python 2 and it should work fine.
